logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    com.itheima: debug
spring:
  rabbitmq:
    host: localhost   # RabbitMQ 服务器的地址
    port: 5672  # 端口
    virtual-host: /hmall  # RabbitMQ 服务器上创建的虚拟主机名
    username: hmall  # 登录 RabbitMQ 服务器的用户名
    password: 123     # 登录 RabbitMQ 服务器的密码
    # 发送者连接失败重连 RabbitMQ 配置
    connection-timeout: 1s  # 设置MQ连接超时时间，即与MQ建立连接超过1s，则认为连接失败
    template:
      retry:
        enabled: true   # 开启超时重试连接机制
        initial-interval: 1000ms    # 失败后的初始等待时间
        multiplier: 1   # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3   # 最大重试次数
    # 发送者开启确认机制
    publisher-returns: true
    publisher-confirm-type: correlated