 sky:
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     host: localhost
     port: 3306
     database: sky_take_out
     username: root
     password: 123
   redis:
     host: localhost
     port: 6379
     database: 0
     #      password: 123456

   # 阿里云OSS配置
   alioss:
     endpoint: 
     access-key-id:
     access-key-secret: 
     bucket-name:

   # 微信小程序相关配置
   wechat:
     appid: wx473128301203e6ea
     secret: 1b9e2de7564e16eb6d19990df22b9bcc
     # 微信支付
     mchid: 1561414331
     mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
     privateKeyFilePath: apiclient_key.pem
     apiV3Key: CZBK51236435wxpay435434323FFDuv3
     weChatPayCertFilePath: wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
     notifyUrl: https://www.weixin.qq.com/wxpay/paySuccess  # 支付成功回调地址
     refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php   # 支付失败回调地址