server:
  port: 9090    # 设置 SpringBoot 项目端口号

# 配置 Spring boot 项目信息
spring:
  application:
    name: project08-spring-db-mybatis
  # 数据库连接信息配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/czm_db03
    username: root
    password: 123

# Mybatis 的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
