server:
  port: 9090    # 设置 SpringBoot 项目端口号

# 配置 Spring boot 项目信息
spring:
  application:
    name: project08-spring-db-mybatis
  # 数据库连接信息配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/czm_db03
    username: root
    password: 123

# Mybatis 的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启Mybatis的日志输出，开启后 sql 语句会在终端显示
    map-underscore-to-camel-case: true    # 开启 Mybatis 结果数据封装时采用驼峰命名映射，如：create_time > createTime
#  mapper-locations: classpath:mapper/*.xml   # 配置XML与Mapper接口的映射路径，即去 main/resources/mapper/ 目录下查找 xml 文件
