version: "3.2"

services:
  # 1、配置 redis 主从集群
  r1:
    image: redis
    container_name: r1
    network_mode: "host"
    entrypoint: ["redis-server", "--port", "7001"]
  # 设置 "--slaveof", "127.0.0.1", "7001" 表示 r2、r3 在启动那一刻就会自动成为 r1 的 slave，就不需要手动配置了。
  r2:
    image: redis
    container_name: r2
    network_mode: "host"
    entrypoint: ["redis-server", "--port", "7002", "--slaveof", "127.0.0.1", "7001"]
  r3:
    image: redis
    container_name: r3
    network_mode: "host"
    entrypoint: ["redis-server", "--port", "7003", "--slaveof", "127.0.0.1", "7001"]
  # 2、配置 redis 哨兵集群
  # 哨兵集群使用的镜像依然是 redis，Redis 即可以部署主从集群，也可以用来部署 哨兵集群。
  s1:
    image: redis
    container_name: s1
    volumes:
      - /Users/chen/Desktop/redis/s1:/etc/redis
    network_mode: "host"
    entrypoint: ["redis-sentinel", "/etc/redis/sentinel.conf", "--port", "27001"]
  s2:
    image: redis
    container_name: s2
    volumes:
      - /Users/chen/Desktop/redis/s2:/etc/redis
    network_mode: "host"
    entrypoint: ["redis-sentinel", "/etc/redis/sentinel.conf", "--port", "27002"]
  s3:
    image: redis
    container_name: s3
    volumes:
      - /Users/chen/Desktop/redis/s3:/etc/redis
    network_mode: "host"
    entrypoint: ["redis-sentinel", "/etc/redis/sentinel.conf", "--port", "27003"]