logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  application:
    name: consumer
  rabbitmq:
    host: 10.0.1.65    # RabbitMQ 服务器的地址 localhost
    port: 5672  # 端口
    virtual-host: /hmall  # RabbitMQ 服务器上创建的虚拟主机名
    username: hmall  # 登录 RabbitMQ 服务器的用户名
    password: 123     # 登录 RabbitMQ 服务器的密码

    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
        acknowledge-mode: auto
        # 配置消费者失败重试机制
        retry:
          enabled: true   # 开启消费者失败重试
          initial-interval: 1000ms    # 初始的失败等待时长为1秒
          multiplier: 1   # 下次失败的等待时长倍数，下次等待时长 = multiplier * initial-interval
          max-attempts: 3   # 最大重试次数
          stateless: true   # true 无状态；false 有状态。如果业务中包含事务，这里改为 false
